#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Deepankar Mahapatro

# Short bio or description (displayed in the header)
description: Still figuring out!

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/9050737?s=400&u=f8ac4cfedae7c6d4baa78270ec13d03b442b9425&v=4

theme: jekyll-theme-cayman